development:
  adapter: postgresql
  encoding: UTF-8
  host:     172.16.10.10
  port:     5432
  database: rave_machine_development
  username: developer
  password:

test:
  adapter: postgresql
  encoding: UTF-8
  host:     172.16.10.10
  port:     5432
  database: rave_machine_test
  username: developer
  password:

production:
  adapter: postgresql
  encoding: UTF-8
  host:     172.16.10.10
  port:     5432
  database: rave_machine_production
  username: rave_machine
  password:
